framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAIL_FROM_EMAIL)%'
        headers:
            From: '%env(MAIL_FROM_NAME)% <%env(MAIL_FROM_EMAIL)%>'
