version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: docker/common/php/Dockerfile
    volumes:
      - ./:/code:rw
    working_dir: /code
    ports:
      - "127.0.0.1:9001:9000"
